name: CI Practica Bloque 1

on:
  push:
    branches: [ "mai" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Paso correcto
      run: echo "Pipeline ejecut√°ndose correctamente"

    - name: Paso con ERROR intencional
      run: echo "Error corregido, pipeline OK"
